# Travis Build Config for FlowstoneEnergy
language: java
  
# Needed to fix Travis<->Windows Permissions
install: []
before_script: 'chmod u+x gradlew'

# Actual Script
script:
- './gradlew setupCIWorkspace build'
